### ISSUE TITLE
Have inventory tracking 

### ISSUE THREAD

**Issue by msg4real** [magfest/tuber#136]
It would be helpful to allow DH to know what magfest inventory is (even if its missing items)

**Comment by bitbyt3r** [comment]
I think this is better implemented outside tuber. We currently use E-ZO for the warehouse inventory, which probably does better than I could in tuber.

**Comment by msg4real** [comment]
I was thinking for items loaned at event just a simple x badge has loaned
{item } to {department} pick date

Has picked up (y/n)

**Comment by msg4real** [comment]
Definitely not items outside of event.. everything must be aquire and
removed between event start and end dates

**Comment by bitbyt3r** [comment]
It would definitely be useful, but one of my main goals in rewriting Uber is to trim it down to a maintainable size. Anything that doesn't directly align to the core goals of tracking the personnel and attendees of the event should probably go elsewhere when possible. That said, it would be easy to implement this as a separate app and call into Tuber to authenticate and get badge and department info.

**Comment by bitbyt3r** [comment]
I am also planning to allow external apps to store some amount of information inside tuber using key-value pairs on most objects, so you could store the fact that someone borrowed something inside tuber without needing a separate database. However there will be limits, such as if you store a loan on a badge object and it gets deleted you would no longer have access to their key-value store and the loaned item would be forgotten. (Though generally badges should not get deleted, so it'll depend on the precise use-case.)

**Comment by msg4real** [comment]
Ty...
