### ISSUE TITLE
Have DH Memo pad

### ISSUE THREAD

**Issue by msg4real** [magfest/tuber#138]
there are times that one department head makes a call or fills out a form but is unable to reach the rest of the heads for input 

or for a spot for the dh to put links to docs they need to look at all the time 

(BUT NOT FOR DISAPLINARY ACCIONS)

**Comment by bitbyt3r** [comment]
I think this would be better implemented outside tuber, as apps like trello already do this a lot better than I could.

**Comment by msg4real** [comment]
Just small notepad for checklists ie) so one could say i filled out
sinageage requesting 1x room sign, covid sign,

Or we need the following for the techops checklist (honestly, there are
some steps that are managed by both heads and one needs to know the output
of the forms) / know what to imput easily

**Comment by bitbyt3r** [comment]
At least for that case I would rather make it easier to see what was entered on each checklist item and by whom, rather than forcing everyone to type it twice, once into the actual form and again into the memo field.

**Comment by msg4real** [comment]
Yes, I agree.
