### ISSUE TITLE
Room Nights weight goes by nights requested, not nights approved.

### ISSUE THREAD

**Issue by outlaw-josiah** [magfest/tuber#14]
Issue is the name on the tin. Luckily, the nights displayed are approved nights, so the user can tell what the problem is at a glance, but it takes up valuable real estate on the recommended section.

**Comment by bitbyt3r** [comment]
Are you certain? I can't reproduce the issue.

**Comment by bitbyt3r** [comment]
Nevermind, I was always including the non-restricted room nights in the list of 'approved' nights, rather than only the intersection of approved and requested nights. This is fixed now.
