### ISSUE TITLE
make tuber multi server

### ISSUE THREAD

**Issue by msg4real** [magfest/tuber#142]
Allow the server to be run on many servers and have over 100,000 connections at once during peak operation

**Comment by bitbyt3r** [comment]
This is already implemented, though as of yet one server has been sufficient. All state is kept in either postgres or redis and is transnational, so we can have as many frontend servers as we want. If we hit the limits of postgres the backend has a circuitbreaker that will start returning asynchronous responses to the frontend, which should already handle them appropriately.

**Comment by msg4real** [comment]
Honestly, uber only needed more than one server during launch when the
hotel lottery thing started idk how much it gets hammered the first week
now
