### ISSUE TITLE
Have custom error pages

### ISSUE THREAD

**Issue by msg4real** [magfest/tuber#143]
don't let the end user know all the code line issues directly use error codes to let the dev team know where to start 

(don't want people to break the code to get free stuff or show ssi)

**Comment by bitbyt3r** [comment]
Tuber shouldn't put stack traces in the frontend (let me know if you find a situation where an API endpoint returns a stack trace). We have Sentry configured to track stack traces so devs can see them without user cooperation.

**Comment by msg4real** [comment]
I was thinking like if tuber is down or experiencing high traffic we could let the user know so the server doesn't get hit with f5 all the time when the user thinks it's them or is impatient 

But, yes! I love that the errors don't have code in users faces

**Comment by bitbyt3r** [comment]
Once the frontend is a bit more stable I'm planning to setup a service worker that will help cache everything client side, and allow some amount of offline functionality. That way even if the user does mash f5 the service worker can prevent the needless pageloads from hitting the backend and can follow a standard backoff if it's getting error responses.

**Comment by msg4real** [comment]
Ty!!! You rock
