### ISSUE TITLE
Days not-requested showing as requested

### ISSUE THREAD

**Issue by faithsavill** [magfest/tuber#15]
Example: Tim Kainzbauer requested Tues/Sun night only, but is showing up as having requested Tu Th Fri Sa Su instead.

**Comment by bitbyt3r** [comment]
This should be fixed now.

**Comment by faithsavill** [comment]
![Screenshot 2019-11-22 at 2 50 23 PM](https://user-images.githubusercontent.com/58088913/69455972-8ee5ab00-0d37-11ea-997d-5721482a6f22.png)

When you move Tim into a room, the room nights change.

**Comment by bitbyt3r** [comment]
Ok, this should be fixed too. Note that anyone already assigned to a room will still be assigned the same way, but new assignments won't include unrestricted nights if they weren't requested.
