### ISSUE TITLE
Make Tuber modular 

### ISSUE THREAD

**Issue by msg4real** [magfest/tuber#155]
I think it would be great if we had a core and everything else was in their own plugins 
core (registration)
+emails
+dhlist
+staffcklist
+food
 -food emails
+crowdmagersindex
+guests
+mivs
+attractions
+stops
+staffrooms
+ect..... 

this way we can use what we need and all the code for functions is in known places

**Comment by bitbyt3r** [comment]
I'm not looking to add a plugin system, as I would much rather push non-core functionality into a completely separate app. Tuber is long-lived, so maintaining plugins in that lifecycle is quite a burden for a young project.
