### ISSUE TITLE
Higher contrast

### ISSUE THREAD

**Issue by faithsavill** [magfest/tuber#19]
This is probably a personal request, but because I am having to view the screen at 50% to get the right search column fully viewable, can we up the contrast (as in, just have all the fonts be black)? If not, it's OK. Thanks!

**Comment by bitbyt3r** [comment]
I can't figure out how to get all the fonts to be black, but I made the font on the roommate cards black and set the search column to scroll separately for the page so you can see all of it on shorter screens. There is also a "Num Matches" slider on the left column that lets you set how many matches show up. I'll keep working on the color issue, this has been mentioned by a few people now. The library I'm using is ignoring my theme settings...
