### ISSUE TITLE
Rework Menu

### ISSUE THREAD

**Issue by bitbyt3r** [magfest/tuber#2]
We should rework the side menu to move to the toolbar on wide screens. Example here: https://gist.github.com/oliverbth05/9834e9114b52b1f4ea77a0ae2d353e2f

Current menu implementation is here: https://github.com/magfest/tuber/blob/master/src/App.vue

Each section should spawn a dropdown menu on click in both the navigation drawer and toolbar format.

**Comment by Sobanim** [comment]
Hello. Can you describe more detail about your issue?
