### ISSUE TITLE
As a person looking for details on a completed room, I would love to be able to search for it quickly

### ISSUE THREAD

**Issue by dlenik** [magfest/tuber#22]
I might just not know the ins and outs of the system, but currently, if I want to find a single completed room among many, I am doing it by unchecking the "hide completed rooms" box and then going page-by-page using ctrl-F to find the person's name.

On a related note, there is no way to quickly see a person's original room request if they are in a completed room, for the same reasons. Maybe could be solved using the existing search bar (which currently only shows people who haven't yet been assigned a room)?

**Comment by bitbyt3r** [comment]
I added a checkbox to the assignment page under the filter section to disable paginating, which should alleviate this partially. I'm going to leave this open until I actually implement a searchable page.
